export const FETCH_SHOWS = "FETCH SHOWS";
export const SET_FETCH_SHOWS_STATUS = "SET FETCH SHOWS STATUS";
export const SHOWS_FETCHED = "SHOWS FETCHED";

export const ADD_SHOW = "ADD SHOW";
export const SET_ADD_SHOW_STATUS = "SET ADD SHOW STATUS";
export const SHOW_ADDED = "SHOW ADDED";

export const REMOVE_SHOW = "REMOVE SHOW";
export const SET_REMOVE_SHOW_STATUS = "SET REMOVE SHOW STATUS";
export const SHOW_REMOVED = "SHOW REMOVED";

export const FETCH_EPISODES = "FETCH EPISODES";
export const SET_FETCH_EPISODES_STATUS = "SET FETCH EPISODES STATUS";
export const EPISODES_LOADED = "EPISODES FETCHED";
export const ADD_EPISODES = "ADD EPISODES";
export const REMOVE_EPISODES = "REMOVE EPISODES";
export const SET_EPISODE_FILTER = "SET EPISODE FILTER"
export const ADD_SHOW_FILTER = "ADD SHOW FILTER"
export const REMOVE_SHOW_FILTER = "REMOVE SHOW FILTER"