export const SHOW_ALL = 'SHOWING: ALL EPISODES';
export const SHOW_FIRST = 'SHOWING: FIRST EPISODES';
export const SHOW_NEXT = 'SHOWING: NEXT EPISODES';
export const SHOW_FUTURE = 'SHOWING: FUTURE EPISODES';
