export const LOAD_SHOWS = "LOAD_SHOWS";
export const SET_LOAD_SHOWS_STATUS = "SET_LOAD_SHOWS_STATUS";
export const SHOWS_LOADED = "SHOWS_LOADED";

export const ADD_SHOW = "ADD_SHOW";
export const SET_ADD_SHOW_STATUS = "SET_ADD_SHOW_STATUS";
export const SHOW_ADDED = "SHOW_ADDED";

export const REMOVE_SHOW = "REMOVE_SHOW";
export const SET_REMOVE_SHOW_STATUS = "SET_REMOVE_SHOW_STATUS";
export const SHOW_REMOVED = "SHOW_REMOVED";

export const LOAD_EPISODES = "LOAD_EPISODES";
export const SET_LOAD_EPISODES_STATUS = "SET_LOAD_EPISODES_STATUS";
export const EPISODES_LOADED = "EPISODES_LOADED";
export const ADD_EPISODES = "ADD_EPISODES";
export const REMOVE_EPISODES = "REMOVE_EPISODES";